name: Continuos Integration

on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
        
    - name: Run unit tests
      run: dotnet test --no-restore --verbosity normal test/NewCelebrities.UnitTests/NewCelebrities.UnitTests.csproj

    - name: Run functional tests
      run: dotnet test --no-restore --verbosity normal test/NewCelebrities.FunctionalTests/NewCelebrities.FunctionalTests.csproj
